### ISSUE TITLE
Low priority: Also put server name, and username#number in database

### ISSUE THREAD

**Issue by LucasPlacentino** [bepolytech/ULBDiscordBot#17]
There's currently no way of identifying the registered servers using only their ID present in the database.
Would be nice to also have it for people's username#number (though there is their full name).

**Comment by OscarVsp** [comment]
I would prefer not to add them to the google sheet since those are not really used in the code and they can change so they should never be used as identifiers to find the corresponding server/user.

However, the bot could get them once the servers/users are loaded (and so even if the name changes, it is always up to date).

For the servers, I can add a similar command than `/user info` for the servers with the `id` and `name#id` (not just `name` since multiple servers could have the exact same name) as parameters, to see if the server is configured and if the `rename` option is enable (and eventually even have the number of registered user on this server and get the list of them).

And for the user name, I can also add a parameters for `username#number`.
